#docker-compose up -d
version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:8.2.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    networks:
      docker-elk:

  kibana:
    image: kibana:8.2.0
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - docker-elk
    depends_on:
      - elasticsearch

networks:
  docker-elk:
    driver: bridge